//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BooksShareMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public long ID { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public long AuthorID { get; set; }
        public long Price { get; set; }
        public Nullable<long> SalePrice { get; set; }
        public long CategoryID { get; set; }
        public Nullable<System.DateTime> PostedOn { get; set; }
        public Nullable<long> CityID { get; set; }
        public string Address { get; set; }
        public Nullable<int> PublicationYear { get; set; }
        public string Language { get; set; }
        public string Mobile { get; set; }
        public string Phone { get; set; }
        public Nullable<long> PictureID { get; set; }
        public Nullable<long> ViewCount { get; set; }
        public Nullable<long> UserID { get; set; }
    
        public virtual Category Category { get; set; }
    }
}
